# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-27 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nickname', models.CharField(max_length=150, verbose_name='昵称')),
                ('username', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=32, verbose_name='password')),
            ],
        ),
    ]
