# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=128)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('c_manager', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contest_Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_source', models.CharField(max_length=128)),
                ('p_id', models.IntegerField()),
                ('p_title', models.CharField(max_length=128)),
                ('c_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_source', models.CharField(max_length=128)),
                ('p_id', models.IntegerField()),
                ('p_title', models.CharField(max_length=128)),
                ('p_description', models.TextField()),
                ('p_input', models.TextField()),
                ('p_output', models.TextField()),
                ('p_sampleinput', models.CharField(max_length=512)),
                ('p_sampleoutput', models.CharField(max_length=512)),
                ('p_url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_source', models.CharField(max_length=128)),
                ('p_id', models.IntegerField()),
                ('p_result', models.CharField(max_length=128)),
                ('p_code', models.TextField()),
                ('Language', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('contest_id', models.IntegerField()),
                ('submitTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
