# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0003_auto_20181202_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='email'),
            preserve_default=False,
        ),
    ]
