# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0004_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='contest_id',
            field=models.IntegerField(null=True),
        ),
    ]
