# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-03 05:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0005_auto_20181226_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['submitTime']},
        ),
    ]
