# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-03 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0007_auto_20190103_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='p_memoryused',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='p_runid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='p_timeused',
            field=models.IntegerField(null=True),
        ),
    ]
