# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0008_auto_20190103_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='p_url',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
