# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0009_auto_20190103_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_problem',
            name='p_title',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
