# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0010_auto_20190117_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='problemInfo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='VirtualJudge.Problem'),
            preserve_default=False,
        ),
    ]
