# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-09 07:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VirtualJudge', '0011_status_probleminfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='problemInfo',
        ),
    ]
